#!/usr/bin/env php
<?php

use PTF\Infrastructure\Ui\Cli\PtfApplicationConfig;
use Webmozart\Console\ConsoleApplication;

require_once __DIR__ . '/vendor/autoload.php';

$container = require __DIR__ . '/app/bootstrap.php';

$cli = new ConsoleApplication(new PtfApplicationConfig(\bitExpert\Disco\BeanFactoryRegistry::getInstance()));

$cli->run();
