#!/usr/bin/env php
<?php

use PTF\Infrastructure\Ui\Cli\PtfApplicationConfig;
use Webmozart\Console\ConsoleApplication;

require_once __DIR__ . '/vendor/autoload.php';

$container = require __DIR__ . '/app/container.php';

$cli = new ConsoleApplication(new PtfApplicationConfig($container));
$cli->run();
