version: '3'

services:
  hexagonal-php-fpm:
    build:
      context: ..
      dockerfile: docker/php-fpm/Dockerfile
    container_name: hexagonal-php-fpm
    links:
      - hexagonal-mysql
    volumes:
      - ..:/app
  hexagonal-mysql:
    image: mysql:latest
    container_name: hexagonal-mysql
    volumes:
      - ./data/mysql:/var/lib/mysql:delegated
    ports:
     - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpass
      MYSQL_DATABASE: hexagonal
      MYSQL_USER: hexagonal
      MYSQL_PASSWORD: hexagonal